# Week 3: Assignment 1

## Download & Prepare Dataset

In [1]:
import pandas as pd

In [2]:
# fetching data from the given URL and storing in dataframe.
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
# original_url = 'https://en.wikipedia.org/w/index.php?title=List_of_postal_codes_of_Canada:_M&oldid=862527922'
df_list = pd.read_html(url)
df = df_list[0]
df.head()

  Postal Code           Borough               Neighborhood
0         M1A      Not assigned                        NaN
1         M2A      Not assigned                        NaN
2         M3A        North York                  Parkwoods
3         M4A        North York           Victoria Village
4         M5A  Downtown Toronto  Regent Park, Harbourfront

In [3]:
# eliminating 'Not assigned' boroughs
df = df[df.Borough != 'Not assigned'].reset_index(drop=True)
df.head()

  Postal Code           Borough                                 Neighborhood
0         M3A        North York                                    Parkwoods
1         M4A        North York                             Victoria Village
2         M5A  Downtown Toronto                    Regent Park, Harbourfront
3         M6A        North York             Lawrence Manor, Lawrence Heights
4         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [4]:
# group by Postal Code and combine neighbourhoods with same postal code
# df = df.groupby(['Postal Code', 'Borough'], as_index=False).agg(lambda x: ', '.join(x))
# df.head()
df['Neighborhood'] = df.groupby(['Postal Code','Borough'])['Neighborhood'].transform(lambda x: ', '.join(x))
df = df.drop_duplicates()
df.reset_index(drop = True, inplace=True)
df.head()

  Postal Code           Borough                                 Neighborhood
0         M3A        North York                                    Parkwoods
1         M4A        North York                             Victoria Village
2         M5A  Downtown Toronto                    Regent Park, Harbourfront
3         M6A        North York             Lawrence Manor, Lawrence Heights
4         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [5]:
# for neighborhoods="Not assigned", neighbourhood == borough
for index, row in df.iterrows():
    if row['Neighborhood'] == 'Not assigned':
        row['Neighborhood'] == row['Borough']
df.head()

  Postal Code           Borough                                 Neighborhood
0         M3A        North York                                    Parkwoods
1         M4A        North York                             Victoria Village
2         M5A  Downtown Toronto                    Regent Park, Harbourfront
3         M6A        North York             Lawrence Manor, Lawrence Heights
4         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [6]:
# converting the transformed dataset into the one as shown in the question

# create a new DataFrame
columns = ['Postal Code', 'Borough', 'Neighborhood']
temp_df = pd.DataFrame(columns=columns)

temp_list = ['M5G', 'M2H', 'M4B', 'M1J', 'M4G', 'M4M', 'M1R', 'M9V', 'M9L', 'M5V', 'M1B', 'M5A']

for pc in temp_list:
    temp_df = temp_df.append(df[df['Postal Code']==pc], ignore_index=True)

temp_df

,Postal Code,Borough,Neighborhood
0,M5G,Downtown Toronto,Central Bay Street
1,M2H,North York,Hillcrest Village
2,M4B,East York,"Parkview Hill, Woodbine Gardens"
3,M1J,Scarborough,Scarborough Village
4,M4G,East York,Leaside
5,M4M,East Toronto,Studio District
6,M1R,Scarborough,"Wexford, Maryvale"
7,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest..."
8,M9L,North York,Humber Summit
9,M5V,Downtown Toronto,"CN Tower, King and Spadina, Railway Lands, Har..."
10,M1B,Scarborough,"Malvern, Rouge"
11,M5A,Downtown Toronto,"Regent Park, Harbourfront"

In [7]:
df.shape

(103, 3)